### ISSUE TITLE
Parsers giving NULL for symbol row locations.

### ISSUE THREAD

**Issue by earwig** [earwig/bitshift#64]
This isn't valid. While columns and end_row can be null, the row should be giving some actual line number. I don't know if this is related to #62.

**Comment by earwig** [comment]
No, I'm talking about the start row, not the end row. Unless I'm missing something, 335027b won't fix that.

**Comment by benattal** [comment]
Can you give me an example of when the start row becomes None?

**Comment by benattal** [comment]
I haven't seen it.

**Comment by earwig** [comment]
Okay, I will find an example repo.

**Comment by earwig** [comment]
It happens when parsing `test/configs/test.rb` in https://github.com/mojombo/god:

```
14-06-08 15:53:05 INFO bitshift.crawler.indexer.GitIndexer:_insert_repository_codelets parsing: https://github.com/mojombo/god, test/configs/test.rb
14-06-08 15:53:05 ERROR bitshift.crawler.indexer.GitIndexer:_index_repository Exception raised while indexing:
Traceback (most recent call last):
  File "bitshift/crawler/indexer.py", line 132, in _index_repository
    self._insert_repository_codelets(repo)
  File "bitshift/crawler/indexer.py", line 178, in _insert_repository_codelets
    self.database.insert(codelet)
  File "bitshift/database/__init__.py", line 223, in insert
    self._insert_symbols(cursor, code_id, sym_type, symbols)
  File "bitshift/database/__init__.py", line 155, in _insert_symbols
    cursor.executemany(query2, params)
  File "cursor.pyx", line 138, in oursql.Cursor.executemany (oursqlx/oursql.c:17073)
  File "statement.pyx", line 402, in oursql._Statement.execute (oursqlx/oursql.c:10904)
  File "statement.pyx", line 127, in oursql._Statement._raise_error (oursqlx/oursql.c:8082)
ProgrammingError: (1048, "Column 'sloc_row' cannot be null", None)
```

**Comment by benattal** [comment]
I thought I had to offset the line numbers, but it turns out I was making row numbers negative, which python interpreted as None.
